package gr.uoa.di.models;
// Generated Mar 29, 2016 1:43:54 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category")
public class Category implements java.io.Serializable {

	private Integer catId;
	private String name;
	private Set<ItemInCat> itemInCats = new HashSet<ItemInCat>(0);

	public Category() {
	}

	public Category(String name, Set<ItemInCat> itemInCats) {
		this.name = name;
		this.itemInCats = itemInCats;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cat_id", unique = true, nullable = false)
	public Integer getCatId() {
		return this.catId;
	}

	public void setCatId(Integer catId) {
		this.catId = catId;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<ItemInCat> getItemInCats() {
		return this.itemInCats;
	}

	public void setItemInCats(Set<ItemInCat> itemInCats) {
		this.itemInCats = itemInCats;
	}

}
