package gr.uoa.di.models;
// Generated Mar 29, 2016 1:43:54 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemInCat generated by hbm2java
 */
@Entity
@Table(name = "item_in_cat")
public class ItemInCat implements java.io.Serializable {

	private ItemInCatId id;
	private Category category;
	private Item item;

	public ItemInCat() {
	}

	public ItemInCat(ItemInCatId id) {
		this.id = id;
	}

	public ItemInCat(ItemInCatId id, Category category, Item item) {
		this.id = id;
		this.category = category;
		this.item = item;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "catId", column = @Column(name = "cat_id") ),
			@AttributeOverride(name = "itemId", column = @Column(name = "item_id") ) })
	public ItemInCatId getId() {
		return this.id;
	}

	public void setId(ItemInCatId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cat_id", insertable = false, updatable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id", insertable = false, updatable = false)
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

}
