package gr.uoa.di.models;
// Generated Mar 29, 2016 1:43:54 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user")
public class User implements java.io.Serializable {

	private Integer userId;
	private String username;
	private String password;
	private String name;
	private String surname;
	private String email;
	private String phone;
	private String afm;
	private String location;
	private Float lat;
	private Float lon;
	private String country;
	private Integer buyerRating;
	private Integer sellerRating;
	private Boolean isAdmin;
	private Boolean isValidated;
	private Set<Bid> bids = new HashSet<Bid>(0);
	private Set<Message> messages = new HashSet<Message>(0);
	private Set<Item> items = new HashSet<Item>(0);
	private Set<Message> messages_1 = new HashSet<Message>(0);

	public User() {
	}

	public User(String username, String password, String name, String surname, String email, String phone, String afm, String location,
			Float lat, Float lon, String country, Integer buyerRating, Integer sellerRating, Boolean isAdmin, Boolean isValidated,
			Set<Bid> bids, Set<Message> messages, Set<Item> items, Set<Message> messages_1) {
		this.username = username;
		this.password = password;
		this.name = name;
		this.surname = surname;
		this.email = email;
		this.phone = phone;
		this.afm = afm;
		this.location = location;
		this.lat = lat;
		this.lon = lon;
		this.country = country;
		this.buyerRating = buyerRating;
		this.sellerRating = sellerRating;
		this.isAdmin = isAdmin;
		this.isValidated = isValidated;
		this.bids = bids;
		this.messages = messages;
		this.items = items;
		this.messages_1 = messages_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "surname", length = 45)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Column(name = "email", length = 60)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "afm", length = 45)
	public String getAfm() {
		return this.afm;
	}

	public void setAfm(String afm) {
		this.afm = afm;
	}

	@Column(name = "location", length = 150)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "lat", precision = 12, scale = 0)
	public Float getLat() {
		return this.lat;
	}

	public void setLat(Float lat) {
		this.lat = lat;
	}

	@Column(name = "lon", precision = 12, scale = 0)
	public Float getLon() {
		return this.lon;
	}

	public void setLon(Float lon) {
		this.lon = lon;
	}

	@Column(name = "country", length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "buyer_rating")
	public Integer getBuyerRating() {
		return this.buyerRating;
	}

	public void setBuyerRating(Integer buyerRating) {
		this.buyerRating = buyerRating;
	}

	@Column(name = "seller_rating")
	public Integer getSellerRating() {
		return this.sellerRating;
	}

	public void setSellerRating(Integer sellerRating) {
		this.sellerRating = sellerRating;
	}

	@Column(name = "is_admin")
	public Boolean getIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(Boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	@Column(name = "is_validated")
	public Boolean getIsValidated() {
		return this.isValidated;
	}

	public void setIsValidated(Boolean isValidated) {
		this.isValidated = isValidated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Bid> getBids() {
		return this.bids;
	}

	public void setBids(Set<Bid> bids) {
		this.bids = bids;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Message> getMessages() {
		return this.messages;
	}

	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Message> getMessages_1() {
		return this.messages_1;
	}

	public void setMessages_1(Set<Message> messages_1) {
		this.messages_1 = messages_1;
	}

}
